Repository EverestAPI/Everest, pull requests merged in 2024-06, with the labels that each got.

#770 fix(search-box): TextBox not consuming buffer
  Celeste.Mod.mm/Mod/UI/TextMenuExt.cs
Labels: needs fixing

#775 Crash handler improvements
  Celeste.Mod.mm/Mod/UI/CriticalErrorHandler.cs
Labels: ready for review

#777 Can set another name for levelset in the filter options of map list.
  Celeste.Mod.mm/Mod/UI/OuiMapList.cs
Labels: ready for review

#771 Make blacklist into hashset
  Celeste.Mod.mm/Mod/Everest/Everest.Loader.cs
  Celeste.Mod.mm/Mod/UI/OuiDependencyDownloader.cs
Labels: needs fixing

#780 Fixes EntityIDs to be consistent for globally generated entities
  Celeste.Mod.mm/Mod/Everest/Everest.Loader.cs
  Celeste.Mod.mm/Patches/EntityData.cs
  Celeste.Mod.mm/Patches/Level.cs
  Celeste.Mod.mm/Patches/LevelData.cs
Labels: needs fixing

#503 Make metadata loading consistent; closes #438
  Celeste.Mod.mm/Mod/Meta/MapMeta.cs
  Celeste.Mod.mm/Patches/AreaData.cs
  Celeste.Mod.mm/Patches/MapData.cs
Labels: needs fixing, should be squashed

#782 Fix code hot reload accidentally loading a cached version
  Celeste.Mod.mm/Mod/Everest/Everest.Loader.cs
  Celeste.Mod.mm/Mod/Module/EverestModuleMetadata.cs
Labels: needs fixing
