Repository EverestAPI/Everest, pull requests merged in 2025-09, with the labels that each got.

#966 Fix crash when trying to apply emoji to null
  Celeste.Mod.mm/Mod/Everest/Emoji.cs
  Celeste.Mod.mm/Patches/Monocle/PixelFontSize.cs
Labels: ready to merge

#980 fix wipedebug console command not doing anything
  Celeste.Mod.mm/Patches/SaveData.cs
Labels: last call window

#975 save command
  Celeste.Mod.mm/Mod/Helpers/Commands.cs
Labels: ready to merge

#976 Update CustomMemorialText.cs to position itself sensibly when level.Zoom =\= 1
  Celeste.Mod.mm/Mod/Entities/CustomMemorialText.cs
Labels: ready to merge

#977 Introduce events for Player.Update and Level.Update.
  Celeste.Mod.mm/Mod/Everest/Everest.Events.cs
  Celeste.Mod.mm/Patches/Level.cs
  Celeste.Mod.mm/Patches/Player.cs
Labels: ready to merge

#985 add event for `GameLoader.LoadThread`
  Celeste.Mod.mm/Mod/Everest/Everest.Events.cs
  Celeste.Mod.mm/Patches/GameLoader.cs
Labels: ready to merge

#972 Deprecate TimeRate for Mods who should use TimeRateModifiers
  Celeste.Mod.mm/Patches/Monocle/Engine.cs
Labels: should be squashed, ready to merge

#987 Allow wrapping when selecting save slot
  Celeste.Mod.mm/Patches/OuiFileSelect.cs
Labels: ready to merge

#990 Splash: Ditch Timers and use deltatime instead
  EverestSplash/EverestSplash.cs
Labels: ready to merge

#992 per decal parallax
  Celeste.Mod.mm/Mod/Everest/Extensions.cs
  Celeste.Mod.mm/Mod/Registry/DecalRegistryHandlers/ParallaxDecalRegistryHandler.cs
  Celeste.Mod.mm/Patches/Decal.cs
  Celeste.Mod.mm/Patches/DecalData.cs
  Celeste.Mod.mm/Patches/Level.cs
  Celeste.Mod.mm/Patches/LevelData.cs
Labels: should be squashed, ready to merge
