Repository EverestAPI/Everest, pull requests merged in 2025-06, with the labels that each got.

#906 Keep FakeWalls from hiding TalkComponentUI (#759)
  Celeste.Mod.mm/Patches/TalkComponent.cs
Labels: ready to merge

#898 Add dependencies and optional dependencies to the cache checksums
  Celeste.Mod.mm/Mod/Everest/Everest.Relinker.cs
  Celeste.Mod.mm/Mod/Module/EverestModuleAssemblyContext.cs
Labels: ready to merge

#901 Fix ignores on tilesets using Everest's TileHandler.
  Celeste.Mod.mm/Patches/Autotiler.cs
Labels: ready to merge

#879 Entity.SourceData and SourceId, provide way to efficiently search by EntityData name
  Celeste.Mod.mm/Mod/Everest/Everest.Loader.cs
  Celeste.Mod.mm/Mod/Everest/Everest.cs
  Celeste.Mod.mm/Mod/Registry/EntityRegistry.cs
  Celeste.Mod.mm/Patches/Level.cs
  Celeste.Mod.mm/Patches/Monocle/Entity.cs
  Celeste.Mod.mm/Patches/Monocle/EntityList.cs
  Celeste.Mod.mm/Patches/Monocle/Scene.cs
  Celeste.Mod.mm/Patches/Monocle/Tracker.cs
Labels: ready to merge

#923 fix typo in Everest Main Class for version commit variable comment
  Celeste.Mod.mm/Mod/Everest/Everest.cs
Labels: review needed

#916 Run Celeste TASes on pull requests
  .github/dependabot.yml
  .github/tas-check/1-get-build-url.sh
  .github/tas-check/2-1-install.sh
  .github/tas-check/2-2-install-inner.sh
  .github/tas-check/3-run.sh
  .github/tas-check/Dockerfile
  .github/tas-check/run-locally.sh
  .github/workflows/tas-sync-check.yml
Labels: last call window

#924 Bump TAS check dependencies
  .github/tas-check/2-1-install.sh
  .github/tas-check/2-2-install-inner.sh
  .github/tas-check/Dockerfile
  .github/tas-check/run-locally.sh
  .github/workflows/tas-sync-check.yml
Labels: review needed

#918 Include Branch [dev|stable|beta] or pr$PullRequestID at end of version string
  .azure-pipelines/prebuild.ps1
Labels: ready to merge

#884 logs the total of loaded modules at launch
  Celeste.Mod.mm/Mod/Everest/Everest.Loader.cs
Labels: should be squashed, ready to merge

#886 Add soundParam attribute for the Tileset XMLs + force a NoInlining on Player.DustParticleFromSurfaceIndex
  Celeste.Mod.mm/MonoModRules.Game.cs
  Celeste.Mod.mm/Patches/Autotiler.cs
  Celeste.Mod.mm/Patches/LevelLoader.cs
  Celeste.Mod.mm/Patches/Player.cs
  Celeste.Mod.mm/Patches/SurfaceIndex.cs
Labels: ready to merge

#928 Make OnEndOfFrame thread safe
  Celeste.Mod.mm/Patches/Monocle/Scene.cs
Labels: ready to merge
